// Generated by diesel_ext
#![allow(unused)]
#![allow(clippy::all)]

// use crate::schemas::*;
use ::diesel::prelude::*;
use serde::Serialize;

use crate::dat_parser::parser::DatGame;
use crate::models::{Console, Rom};
use crate::schemas::games::*;

#[derive(Queryable, Debug, Selectable, Serialize, Identifiable, Associations, PartialEq, Clone)]
#[diesel(belongs_to(Console))]
#[diesel(table_name = games)]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
pub struct Game {
    pub id: i32,
    pub title: String,
    pub console_id: i32,
}

#[derive(Insertable, Debug)]
// #[diesel(belongs_to(Console))]
#[diesel(table_name = games)]
pub struct NewGame<'a> {
    pub title: &'a str,
    pub console_id: i32,
}

impl<'a> NewGame<'a> {
    pub fn from_dat(dat_game: &'a DatGame, console_db_id: Option<i32>) -> Self {
        NewGame {
            title: &dat_game.name,
            console_id: console_db_id.unwrap_or(0),
        }
    }
}

#[derive(Serialize, Debug, Clone)]
pub struct GameWithRoms {
    #[serde(flatten)]
    pub game: Game,
    pub roms: Vec<Rom>,
}
